var mongoose = require('mongoose');

// Create a user model, _id will be automatically generated by Mongoose service
var userSchema = new mongoose.Schema({
  firstname: String,
  lastname: String,
  canvasModels: { type: Object}
});

// Make User available to rest of the application
module.exports = mongoose.model('User', userSchema);
